articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete')
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
                  path('', ArticleListView.as_view(), name='home'),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('articles/', include('articleapp.urls')),
                  path('comments/', include('commentapp.urls')),
                  path('projects/', include('projectapp.urls')),
                  path('subscribe/', include('subscribeapp.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)
    title = models.CharField(max_length=200, null=False)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_on = models.DateField(auto_created=True, null=True)

templates/snippets/list_fragment.html
{% load static %}
<style>

    .container {
        padding: 0;
        margin: 0 auto;
    }

    .container a {
        width: 42%;
        max-width: 250px;
    }

    .container div {
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 8px;
    }

    .container img {
        width: 100%;
        border-radius: 8px;
    }

</style>

{% if article_list %}
    <div class="container">
        {% for article in article_list %}
            <a href="{% url 'articleapp:detail' pk=article.pk %}">
                <img src="{{ article.image.url }}" style="max-width: 15rem">
                <p style="color: black; text-decoration: none; text-align: center; margin-top: 0.5rem">{{ article.title }}</p>
            </a>
        {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
    <div style="text-align: center">
        No Articles Yet
    </div>
{% endif %}

{% include 'snippets/pagination.html' with page_obj=page_obj %}

<div style="text-align: center">
    <a href="{% url 'articleapp:create' %}" class="btn btn-dark col-6 mt-3 mb-3">
        Post an Article
    </a>
</div>

templates/snippets/pagination.html
<div style="text-align: center; margin: 1rem 0;">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-secondary rounded-pill">
            {{ page_obj.previous_page_number }}
        </a>
    {% endif %}
    <a href="?page={{ page_obj.number }}" class="btn btn-secondary rounded-pill active">
        {{ page_obj.number }}
    </a>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-secondary rounded-pill">
            {{ page_obj.next_page_number }}
        </a>
    {% endif %}

</div>