accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete')
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
                  path('', ArticleListView.as_view(), name='home'),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('articles/', include('articleapp.urls')),
                  path('comments/', include('commentapp.urls')),
                  path('projects/', include('projectapp.urls')),
                  path('subscribe/', include('subscribeapp.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectListView, ProjectDetailView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail')
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list')
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{%  include 'head.html' %}

<body >
    {% include 'header.html' %}

    <hr/>

    {% block content %}

    {% endblock %}

    <hr/>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div style="text-align: center; margin-top: 2rem;">

    <div class="footer_buttons">
        <span>공지사항</span> |
        <span>제휴 문의</span> |
        <span>서비스 소개</span>
    </div>

    <div style="margin-top: 1rem;">
        <h6 class="bokdol_footer_logo">BokDol</h6>
    </div>

</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BokDol</title>

    {#  Bootstrap CSS  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    {#  Google Font  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dongle:wght@300&family=Nunito:wght@200&family=Pacifico&display=swap"
          rel="stylesheet">
    {#  Base CSS  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {# Material Icon #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
          rel="stylesheet">
</head>

templates/header.html
<div style="text-align: center; margin: 2rem 0;">
    <div class="bokdol_header_logo">
        <a href="{% url 'home' %}" style="text-decoration: none; color: black">
            <h1>BokDol</h1>
        </a>
    </div>
    <div class="header_navs" style="margin-top: 1rem">
        <a href="{% url 'articleapp:list' %}"
           style="margin: 1rem 1rem; color: black; text-decoration: none;">Articles</a>
        <a href="{% url 'projectapp:list' %}"
           style="margin: 1rem 1rem; color: black; text-decoration: none;">Projects</a>
        {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}"
               style="margin: 1rem 1rem; color: black; text-decoration: none;"><span>Login</span></a>
            <a href="{% url 'accountapp:create' %}?next={{ request.path }}"
               style="margin: 1rem 1rem; color: black; text-decoration: none;"><span>Sign Up</span></a>
        {% else %}
            <a href="{% url 'subscribeapp:list' %}"
               style="margin: 1rem 1rem; color: black; text-decoration: none;">Subscription</a>
            <a href="{% url 'accountapp:detail' pk=user.pk %}"
               style="margin: 1rem 1rem; color: black; text-decoration: none;">My Page</a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}"
               style="margin: 1rem 1rem; color: black; text-decoration: none;"><span>Logout</span></a>
        {% endif %}
    </div>
</div>